spring.application.name=ApiGateway

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.main.web-application-type=reactive
jwt.secret=MySuperSecretKey1234567890123456

# Route for product-service
spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=http://localhost:8084
spring.cloud.gateway.routes[0].predicates[0]=Path=/product/**

# Route for vendor-service
spring.cloud.gateway.routes[1].id=vendor-service
spring.cloud.gateway.routes[1].uri=http://localhost:8083
spring.cloud.gateway.routes[1].predicates[0]=Path=/admin/vendors/**

# Route for auth-service
spring.cloud.gateway.routes[2].id=auth-service
spring.cloud.gateway.routes[2].uri=http://localhost:8081
spring.cloud.gateway.routes[2].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[3].id=user-service
spring.cloud.gateway.routes[3].uri=http://localhost:8082
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/users/**


# Route for payment-service
spring.cloud.gateway.routes[4].id=payment-service
spring.cloud.gateway.routes[4].uri=http://localhost:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/payment/**

# Route for order-service
spring.cloud.gateway.routes[5].id=order-service
spring.cloud.gateway.routes[5].uri=http://localhost:8086
spring.cloud.gateway.routes[5].predicates[0]=Path=/order/**

# Route for schedular-service
spring.cloud.gateway.routes[6].id=schedular-service
spring.cloud.gateway.routes[6].uri=http://localhost:8087
spring.cloud.gateway.routes[6].predicates[0]=Path=/schedular/**